#ifndef OFDPA_TABLES_NUMBER
#define OFDPA_TABLES_NUMBER

enum OFDPA_TABLES
{
    INGRESS = 0,
    VLAN = 10,
    VLAN1 = 11,
    MPLS_L2 = 13,
    TMAC = 20,
    MPLS_0 = 23,
    MPLS_1 = 24,
    MPLS_2 = 25,
    MAINTENANCE_POINT = 26,
    UNICAST_ROUTING = 30,
    MULTICAST_ROUTING = 40,
    BRIDGING = 50,
    POLICY_ACL = 60,
    COLOR_BASED_ACTIONS = 65,
    EGRESS_VLAN = 210,
    EGRESS_VLAN1 = 211,
    EGRESS_MAINTENANCE_POINT = 226,
    SOURCE_MAC_LEARNING = 254
};

#endif